### PR TITLE
Sanity is configured and ready for use.

### PR DESCRIPTION
**Pull request by meshackm**
#14 

# 📲 What was done

A short description with bullet points of what was done.
- I created a sanity dataset in sanity.io
- I created a sanity project in the Next app and added a sample Landing schema
- Added a playground as per @bob606 's idea
- Added sanity's cdn in next.config.js, this is required when using next/image [read more](https://nextjs.org/docs/messages/next-image-unconfigured-host)
- I added a sample query and displayed the data in the playground route. 

# 👀 See

Jira, Figma, Vercel preview, screenshots, external resources?

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# 📋 QA
To see how sanity works in the project, spin up a dev server and open http://localhost:3000/studio in the browser. The studio's page.tsx file can be found in app/[[...index]]/studio. In another tab open http://localhost:3000/playground, here you'll find the heading, image and subheading. Make changes in the studio and refresh the playground to see them in real-time. 

N/B: We will need to implement on-demand revalidation for changes done in the studio to reflect in the deployed site. Content created in studio while in localhost will reflect in localhost, this does not mean it will be the same for the deployment. 

# ☑️ Checklist
- [x] functional criteria and acceptance criteria are fulfiled
- [x] all subtasks are "ready for review"
- [x] spelling is checked
- [x] coding standards and internal conventions are followed

checked on different dimensions:
- [ ] large desktop:  2560 x 1440
- [ ] desktop/laptop: 1920 x 1080
- [ ] tablet:         768 x 1024
- [ ] mobile:         414 x 896

checked on different browsers:
- [x] Chrome
- [ ] Safari
- [ ] Firefox

### CODE REVIEW

**Comment by meshackm** [comment]
Let me fix the build errors caused by sanity.config.ts then you can review

**Comment by meshackm** [comment]
Done!

**Review by bob606 — DISMISSED** [review]
I love everything about this PR. 

For me a suggestion would be to set-up a separate page called sanity-playground, rename the landing section in Sanity into playground and actually showcase the image, heading and subheading functionality there, instead of the current landing page.
That way we can keep examples to that playground without confusing somebody with sections which look like production code but really are only there to play around. What do you think? 

If you disagree with my proposal, you can also just merge, since all the acceptance criteria is very well fulfilled :rocket:

**Comment by bob606** [comment]
@meshack254 I renamed the playgrounds URL otherwise I approve on all changes. If you are okay with that, you can approve and merge.

**Review by bob606 — APPROVED** [review]

**Review by meshackm — COMMENTED** [review]
The rename is okay, am going to merge.

**Pull request merged**
